/**
 *  Copyright (c) 2016-2024 CentraleSupélec & EDF.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v2.0
 *  which accompanies this distribution, and is available at
 *  https://www.eclipse.org/legal/epl-v20.html
 *
 *  This file is part of the RiseClipse tool
 *
 *  Contributors:
 *      Computer Science Department, CentraleSupélec
 *      EDF R&D
 *  Contacts:
 *      dominique.marcadet@centralesupelec.fr
 *      aurelie.dehouck-neveu@edf.fr
 *  Web site:
 *      https://riseclipse.github.io/
 *
 */
package fr.centralesupelec.edf.riseclipse.iec61850.asd.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import fr.centralesupelec.edf.riseclipse.iec61850.asd.util.AsdAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class AsdItemProviderAdapterFactory extends AsdAdapterFactory
        implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
    /**
     * This keeps track of the root adapter factory that delegates to this adapter factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ComposedAdapterFactory parentAdapterFactory;

    /**
     * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected IChangeNotifier changeNotifier = new ChangeNotifier();

    /**
     * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected Collection< Object > supportedTypes = new ArrayList< >();

    /**
     * This constructs an instance.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public AsdItemProviderAdapterFactory() {
        supportedTypes.add( IEditingDomainItemProvider.class );
        supportedTypes.add( IStructuredItemContentProvider.class );
        supportedTypes.add( ITreeItemContentProvider.class );
        supportedTypes.add( IItemLabelProvider.class );
        supportedTypes.add( IItemPropertySource.class );
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.AllocationRole} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected AllocationRoleItemProvider allocationRoleItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.AllocationRole}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createAllocationRoleAdapter() {
        if( allocationRoleItemProvider == null ) {
            allocationRoleItemProvider = new AllocationRoleItemProvider( this );
        }

        return allocationRoleItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.AllocationRoleRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected AllocationRoleRefItemProvider allocationRoleRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.AllocationRoleRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createAllocationRoleRefAdapter() {
        if( allocationRoleRefItemProvider == null ) {
            allocationRoleRefItemProvider = new AllocationRoleRefItemProvider( this );
        }

        return allocationRoleRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.Application} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ApplicationItemProvider applicationItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.Application}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createApplicationAdapter() {
        if( applicationItemProvider == null ) {
            applicationItemProvider = new ApplicationItemProvider( this );
        }

        return applicationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.AnalogueWiringParameters} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected AnalogueWiringParametersItemProvider analogueWiringParametersItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.AnalogueWiringParameters}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createAnalogueWiringParametersAdapter() {
        if( analogueWiringParametersItemProvider == null ) {
            analogueWiringParametersItemProvider = new AnalogueWiringParametersItemProvider( this );
        }

        return analogueWiringParametersItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.AnalogueWiringParametersRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected AnalogueWiringParametersRefItemProvider analogueWiringParametersRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.AnalogueWiringParametersRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createAnalogueWiringParametersRefAdapter() {
        if( analogueWiringParametersRefItemProvider == null ) {
            analogueWiringParametersRefItemProvider = new AnalogueWiringParametersRefItemProvider( this );
        }

        return analogueWiringParametersRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ApplicationSclRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ApplicationSclRefItemProvider applicationSclRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ApplicationSclRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createApplicationSclRefAdapter() {
        if( applicationSclRefItemProvider == null ) {
            applicationSclRefItemProvider = new ApplicationSclRefItemProvider( this );
        }

        return applicationSclRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.BayType} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected BayTypeItemProvider bayTypeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.BayType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createBayTypeAdapter() {
        if( bayTypeItemProvider == null ) {
            bayTypeItemProvider = new BayTypeItemProvider( this );
        }

        return bayTypeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.BehaviorDescription} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected BehaviorDescriptionItemProvider behaviorDescriptionItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.BehaviorDescription}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createBehaviorDescriptionAdapter() {
        if( behaviorDescriptionItemProvider == null ) {
            behaviorDescriptionItemProvider = new BehaviorDescriptionItemProvider( this );
        }

        return behaviorDescriptionItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.BehaviorDescriptionRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected BehaviorDescriptionRefItemProvider behaviorDescriptionRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.BehaviorDescriptionRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createBehaviorDescriptionRefAdapter() {
        if( behaviorDescriptionRefItemProvider == null ) {
            behaviorDescriptionRefItemProvider = new BehaviorDescriptionRefItemProvider( this );
        }

        return behaviorDescriptionRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.BehaviorReference} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected BehaviorReferenceItemProvider behaviorReferenceItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.BehaviorReference}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createBehaviorReferenceAdapter() {
        if( behaviorReferenceItemProvider == null ) {
            behaviorReferenceItemProvider = new BehaviorReferenceItemProvider( this );
        }

        return behaviorReferenceItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.BinaryWiringParameters} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected BinaryWiringParametersItemProvider binaryWiringParametersItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.BinaryWiringParameters}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createBinaryWiringParametersAdapter() {
        if( binaryWiringParametersItemProvider == null ) {
            binaryWiringParametersItemProvider = new BinaryWiringParametersItemProvider( this );
        }

        return binaryWiringParametersItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.BinaryWiringParametersRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected BinaryWiringParametersRefItemProvider binaryWiringParametersRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.BinaryWiringParametersRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createBinaryWiringParametersRefAdapter() {
        if( binaryWiringParametersRefItemProvider == null ) {
            binaryWiringParametersRefItemProvider = new BinaryWiringParametersRefItemProvider( this );
        }

        return binaryWiringParametersRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.CheckoutID} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected CheckoutIDItemProvider checkoutIDItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.CheckoutID}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createCheckoutIDAdapter() {
        if( checkoutIDItemProvider == null ) {
            checkoutIDItemProvider = new CheckoutIDItemProvider( this );
        }

        return checkoutIDItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ControlRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ControlRefItemProvider controlRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ControlRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createControlRefAdapter() {
        if( controlRefItemProvider == null ) {
            controlRefItemProvider = new ControlRefItemProvider( this );
        }

        return controlRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.CommServiceSpecifications} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected CommServiceSpecificationsItemProvider commServiceSpecificationsItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.CommServiceSpecifications}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createCommServiceSpecificationsAdapter() {
        if( commServiceSpecificationsItemProvider == null ) {
            commServiceSpecificationsItemProvider = new CommServiceSpecificationsItemProvider( this );
        }

        return commServiceSpecificationsItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ControllingLNode} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ControllingLNodeItemProvider controllingLNodeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ControllingLNode}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createControllingLNodeAdapter() {
        if( controllingLNodeItemProvider == null ) {
            controllingLNodeItemProvider = new ControllingLNodeItemProvider( this );
        }

        return controllingLNodeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.DAS} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected DASItemProvider dasItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.DAS}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createDASAdapter() {
        if( dasItemProvider == null ) {
            dasItemProvider = new DASItemProvider( this );
        }

        return dasItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.DOS} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected DOSItemProvider dosItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.DOS}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createDOSAdapter() {
        if( dosItemProvider == null ) {
            dosItemProvider = new DOSItemProvider( this );
        }

        return dosItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionCategory} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected FunctionCategoryItemProvider functionCategoryItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionCategory}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createFunctionCategoryAdapter() {
        if( functionCategoryItemProvider == null ) {
            functionCategoryItemProvider = new FunctionCategoryItemProvider( this );
        }

        return functionCategoryItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionCategoryRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected FunctionCategoryRefItemProvider functionCategoryRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionCategoryRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createFunctionCategoryRefAdapter() {
        if( functionCategoryRefItemProvider == null ) {
            functionCategoryRefItemProvider = new FunctionCategoryRefItemProvider( this );
        }

        return functionCategoryRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionCatRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected FunctionCatRefItemProvider functionCatRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionCatRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createFunctionCatRefAdapter() {
        if( functionCatRefItemProvider == null ) {
            functionCatRefItemProvider = new FunctionCatRefItemProvider( this );
        }

        return functionCatRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected FunctionRefItemProvider functionRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createFunctionRefAdapter() {
        if( functionRefItemProvider == null ) {
            functionRefItemProvider = new FunctionRefItemProvider( this );
        }

        return functionRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionRole} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected FunctionRoleItemProvider functionRoleItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionRole}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createFunctionRoleAdapter() {
        if( functionRoleItemProvider == null ) {
            functionRoleItemProvider = new FunctionRoleItemProvider( this );
        }

        return functionRoleItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionRoleContent} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected FunctionRoleContentItemProvider functionRoleContentItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionRoleContent}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createFunctionRoleContentAdapter() {
        if( functionRoleContentItemProvider == null ) {
            functionRoleContentItemProvider = new FunctionRoleContentItemProvider( this );
        }

        return functionRoleContentItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionSclRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected FunctionSclRefItemProvider functionSclRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionSclRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createFunctionSclRefAdapter() {
        if( functionSclRefItemProvider == null ) {
            functionSclRefItemProvider = new FunctionSclRefItemProvider( this );
        }

        return functionSclRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionTemplate} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected FunctionTemplateItemProvider functionTemplateItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionTemplate}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createFunctionTemplateAdapter() {
        if( functionTemplateItemProvider == null ) {
            functionTemplateItemProvider = new FunctionTemplateItemProvider( this );
        }

        return functionTemplateItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionalSubVariant} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected FunctionalSubVariantItemProvider functionalSubVariantItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionalSubVariant}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createFunctionalSubVariantAdapter() {
        if( functionalSubVariantItemProvider == null ) {
            functionalSubVariantItemProvider = new FunctionalSubVariantItemProvider( this );
        }

        return functionalSubVariantItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionalVariant} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected FunctionalVariantItemProvider functionalVariantItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionalVariant}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createFunctionalVariantAdapter() {
        if( functionalVariantItemProvider == null ) {
            functionalVariantItemProvider = new FunctionalVariantItemProvider( this );
        }

        return functionalVariantItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionalVariantGroup} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected FunctionalVariantGroupItemProvider functionalVariantGroupItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionalVariantGroup}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createFunctionalVariantGroupAdapter() {
        if( functionalVariantGroupItemProvider == null ) {
            functionalVariantGroupItemProvider = new FunctionalVariantGroupItemProvider( this );
        }

        return functionalVariantGroupItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionalVariantRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected FunctionalVariantRefItemProvider functionalVariantRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.FunctionalVariantRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createFunctionalVariantRefAdapter() {
        if( functionalVariantRefItemProvider == null ) {
            functionalVariantRefItemProvider = new FunctionalVariantRefItemProvider( this );
        }

        return functionalVariantRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.GooseParameters} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected GooseParametersItemProvider gooseParametersItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.GooseParameters}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createGooseParametersAdapter() {
        if( gooseParametersItemProvider == null ) {
            gooseParametersItemProvider = new GooseParametersItemProvider( this );
        }

        return gooseParametersItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.GooseParametersRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected GooseParametersRefItemProvider gooseParametersRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.GooseParametersRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createGooseParametersRefAdapter() {
        if( gooseParametersRefItemProvider == null ) {
            gooseParametersRefItemProvider = new GooseParametersRefItemProvider( this );
        }

        return gooseParametersRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.InputVar} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected InputVarItemProvider inputVarItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.InputVar}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createInputVarAdapter() {
        if( inputVarItemProvider == null ) {
            inputVarItemProvider = new InputVarItemProvider( this );
        }

        return inputVarItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.InputVarRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected InputVarRefItemProvider inputVarRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.InputVarRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createInputVarRefAdapter() {
        if( inputVarRefItemProvider == null ) {
            inputVarRefItemProvider = new InputVarRefItemProvider( this );
        }

        return inputVarRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.L2CommParameters} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected L2CommParametersItemProvider l2CommParametersItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.L2CommParameters}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createL2CommParametersAdapter() {
        if( l2CommParametersItemProvider == null ) {
            l2CommParametersItemProvider = new L2CommParametersItemProvider( this );
        }

        return l2CommParametersItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.L3IPv4CommParameters} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected L3IPv4CommParametersItemProvider l3IPv4CommParametersItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.L3IPv4CommParameters}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createL3IPv4CommParametersAdapter() {
        if( l3IPv4CommParametersItemProvider == null ) {
            l3IPv4CommParametersItemProvider = new L3IPv4CommParametersItemProvider( this );
        }

        return l3IPv4CommParametersItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.L3IPv6CommParameters} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected L3IPv6CommParametersItemProvider l3IPv6CommParametersItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.L3IPv6CommParameters}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createL3IPv6CommParametersAdapter() {
        if( l3IPv6CommParametersItemProvider == null ) {
            l3IPv6CommParametersItemProvider = new L3IPv6CommParametersItemProvider( this );
        }

        return l3IPv6CommParametersItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.LNodeDataRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected LNodeDataRefItemProvider lNodeDataRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.LNodeDataRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createLNodeDataRefAdapter() {
        if( lNodeDataRefItemProvider == null ) {
            lNodeDataRefItemProvider = new LNodeDataRefItemProvider( this );
        }

        return lNodeDataRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.LNodeInputRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected LNodeInputRefItemProvider lNodeInputRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.LNodeInputRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createLNodeInputRefAdapter() {
        if( lNodeInputRefItemProvider == null ) {
            lNodeInputRefItemProvider = new LNodeInputRefItemProvider( this );
        }

        return lNodeInputRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.LNodeInputs} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected LNodeInputsItemProvider lNodeInputsItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.LNodeInputs}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createLNodeInputsAdapter() {
        if( lNodeInputsItemProvider == null ) {
            lNodeInputsItemProvider = new LNodeInputsItemProvider( this );
        }

        return lNodeInputsItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.LNodeOutputRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected LNodeOutputRefItemProvider lNodeOutputRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.LNodeOutputRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createLNodeOutputRefAdapter() {
        if( lNodeOutputRefItemProvider == null ) {
            lNodeOutputRefItemProvider = new LNodeOutputRefItemProvider( this );
        }

        return lNodeOutputRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.LNodeOutputs} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected LNodeOutputsItemProvider lNodeOutputsItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.LNodeOutputs}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createLNodeOutputsAdapter() {
        if( lNodeOutputsItemProvider == null ) {
            lNodeOutputsItemProvider = new LNodeOutputsItemProvider( this );
        }

        return lNodeOutputsItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.LNodeSpecNaming} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected LNodeSpecNamingItemProvider lNodeSpecNamingItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.LNodeSpecNaming}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createLNodeSpecNamingAdapter() {
        if( lNodeSpecNamingItemProvider == null ) {
            lNodeSpecNamingItemProvider = new LNodeSpecNamingItemProvider( this );
        }

        return lNodeSpecNamingItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.LogParameters} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected LogParametersItemProvider logParametersItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.LogParameters}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createLogParametersAdapter() {
        if( logParametersItemProvider == null ) {
            logParametersItemProvider = new LogParametersItemProvider( this );
        }

        return logParametersItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.LogParametersRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected LogParametersRefItemProvider logParametersRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.LogParametersRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createLogParametersRefAdapter() {
        if( logParametersRefItemProvider == null ) {
            logParametersRefItemProvider = new LogParametersRefItemProvider( this );
        }

        return logParametersRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.LogicVarRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected LogicVarRefItemProvider logicVarRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.LogicVarRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createLogicVarRefAdapter() {
        if( logicVarRefItemProvider == null ) {
            logicVarRefItemProvider = new LogicVarRefItemProvider( this );
        }

        return logicVarRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.OutputVar} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected OutputVarItemProvider outputVarItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.OutputVar}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createOutputVarAdapter() {
        if( outputVarItemProvider == null ) {
            outputVarItemProvider = new OutputVarItemProvider( this );
        }

        return outputVarItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.OutputVarRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected OutputVarRefItemProvider outputVarRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.OutputVarRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createOutputVarRefAdapter() {
        if( outputVarRefItemProvider == null ) {
            outputVarRefItemProvider = new OutputVarRefItemProvider( this );
        }

        return outputVarRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.PowerSystemRelation} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected PowerSystemRelationItemProvider powerSystemRelationItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.PowerSystemRelation}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createPowerSystemRelationAdapter() {
        if( powerSystemRelationItemProvider == null ) {
            powerSystemRelationItemProvider = new PowerSystemRelationItemProvider( this );
        }

        return powerSystemRelationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.PowerSystemRelationRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected PowerSystemRelationRefItemProvider powerSystemRelationRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.PowerSystemRelationRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createPowerSystemRelationRefAdapter() {
        if( powerSystemRelationRefItemProvider == null ) {
            powerSystemRelationRefItemProvider = new PowerSystemRelationRefItemProvider( this );
        }

        return powerSystemRelationRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.PowerSystemRelations} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected PowerSystemRelationsItemProvider powerSystemRelationsItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.PowerSystemRelations}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createPowerSystemRelationsAdapter() {
        if( powerSystemRelationsItemProvider == null ) {
            powerSystemRelationsItemProvider = new PowerSystemRelationsItemProvider( this );
        }

        return powerSystemRelationsItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ProcessEcho} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ProcessEchoItemProvider processEchoItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ProcessEcho}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createProcessEchoAdapter() {
        if( processEchoItemProvider == null ) {
            processEchoItemProvider = new ProcessEchoItemProvider( this );
        }

        return processEchoItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ProcessResource} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ProcessResourceItemProvider processResourceItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ProcessResource}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createProcessResourceAdapter() {
        if( processResourceItemProvider == null ) {
            processResourceItemProvider = new ProcessResourceItemProvider( this );
        }

        return processResourceItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ProcessResourceRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ProcessResourceRefItemProvider processResourceRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ProcessResourceRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createProcessResourceRefAdapter() {
        if( processResourceRefItemProvider == null ) {
            processResourceRefItemProvider = new ProcessResourceRefItemProvider( this );
        }

        return processResourceRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ProcessResources} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ProcessResourcesItemProvider processResourcesItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ProcessResources}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createProcessResourcesAdapter() {
        if( processResourcesItemProvider == null ) {
            processResourcesItemProvider = new ProcessResourcesItemProvider( this );
        }

        return processResourcesItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.Project} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ProjectItemProvider projectItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.Project}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createProjectAdapter() {
        if( projectItemProvider == null ) {
            projectItemProvider = new ProjectItemProvider( this );
        }

        return projectItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ProjectProcessReference} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ProjectProcessReferenceItemProvider projectProcessReferenceItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ProjectProcessReference}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createProjectProcessReferenceAdapter() {
        if( projectProcessReferenceItemProvider == null ) {
            projectProcessReferenceItemProvider = new ProjectProcessReferenceItemProvider( this );
        }

        return projectProcessReferenceItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ReportParameters} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ReportParametersItemProvider reportParametersItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ReportParameters}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createReportParametersAdapter() {
        if( reportParametersItemProvider == null ) {
            reportParametersItemProvider = new ReportParametersItemProvider( this );
        }

        return reportParametersItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ReportParametersRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ReportParametersRefItemProvider reportParametersRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ReportParametersRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createReportParametersRefAdapter() {
        if( reportParametersRefItemProvider == null ) {
            reportParametersRefItemProvider = new ReportParametersRefItemProvider( this );
        }

        return reportParametersRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.Resource} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ResourceItemProvider resourceItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.Resource}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createResourceAdapter() {
        if( resourceItemProvider == null ) {
            resourceItemProvider = new ResourceItemProvider( this );
        }

        return resourceItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.SDS} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SDSItemProvider sdsItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.SDS}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSDSAdapter() {
        if( sdsItemProvider == null ) {
            sdsItemProvider = new SDSItemProvider( this );
        }

        return sdsItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ServiceParametersRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ServiceParametersRefItemProvider serviceParametersRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ServiceParametersRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createServiceParametersRefAdapter() {
        if( serviceParametersRefItemProvider == null ) {
            serviceParametersRefItemProvider = new ServiceParametersRefItemProvider( this );
        }

        return serviceParametersRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ServiceSpecifications} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ServiceSpecificationsItemProvider serviceSpecificationsItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.ServiceSpecifications}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createServiceSpecificationsAdapter() {
        if( serviceSpecificationsItemProvider == null ) {
            serviceSpecificationsItemProvider = new ServiceSpecificationsItemProvider( this );
        }

        return serviceSpecificationsItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.SignalRole} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SignalRoleItemProvider signalRoleItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.SignalRole}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSignalRoleAdapter() {
        if( signalRoleItemProvider == null ) {
            signalRoleItemProvider = new SignalRoleItemProvider( this );
        }

        return signalRoleItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.SourceRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SourceRefItemProvider sourceRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.SourceRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSourceRefAdapter() {
        if( sourceRefItemProvider == null ) {
            sourceRefItemProvider = new SourceRefItemProvider( this );
        }

        return sourceRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.SubCategory} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SubCategoryItemProvider subCategoryItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.SubCategory}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSubCategoryAdapter() {
        if( subCategoryItemProvider == null ) {
            subCategoryItemProvider = new SubCategoryItemProvider( this );
        }

        return subCategoryItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.SubCheckoutID} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SubCheckoutIDItemProvider subCheckoutIDItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.SubCheckoutID}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSubCheckoutIDAdapter() {
        if( subCheckoutIDItemProvider == null ) {
            subCheckoutIDItemProvider = new SubCheckoutIDItemProvider( this );
        }

        return subCheckoutIDItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.SubFunctionTemplate} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SubFunctionTemplateItemProvider subFunctionTemplateItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.SubFunctionTemplate}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSubFunctionTemplateAdapter() {
        if( subFunctionTemplateItemProvider == null ) {
            subFunctionTemplateItemProvider = new SubFunctionTemplateItemProvider( this );
        }

        return subFunctionTemplateItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.SMVParameters} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SMVParametersItemProvider smvParametersItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.SMVParameters}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSMVParametersAdapter() {
        if( smvParametersItemProvider == null ) {
            smvParametersItemProvider = new SMVParametersItemProvider( this );
        }

        return smvParametersItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.SMVParametersRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SMVParametersRefItemProvider smvParametersRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.SMVParametersRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSMVParametersRefAdapter() {
        if( smvParametersRefItemProvider == null ) {
            smvParametersRefItemProvider = new SMVParametersRefItemProvider( this );
        }

        return smvParametersRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.SubscriberLNode} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SubscriberLNodeItemProvider subscriberLNodeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.SubscriberLNode}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSubscriberLNodeAdapter() {
        if( subscriberLNodeItemProvider == null ) {
            subscriberLNodeItemProvider = new SubscriberLNodeItemProvider( this );
        }

        return subscriberLNodeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.Variable} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected VariableItemProvider variableItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.Variable}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createVariableAdapter() {
        if( variableItemProvider == null ) {
            variableItemProvider = new VariableItemProvider( this );
        }

        return variableItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.VariableApplyTo} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected VariableApplyToItemProvider variableApplyToItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.VariableApplyTo}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createVariableApplyToAdapter() {
        if( variableApplyToItemProvider == null ) {
            variableApplyToItemProvider = new VariableApplyToItemProvider( this );
        }

        return variableApplyToItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.VariableRef} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected VariableRefItemProvider variableRefItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.VariableRef}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createVariableRefAdapter() {
        if( variableRefItemProvider == null ) {
            variableRefItemProvider = new VariableRefItemProvider( this );
        }

        return variableRefItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.WiringParameters} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected WiringParametersItemProvider wiringParametersItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.edf.riseclipse.iec61850.asd.WiringParameters}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createWiringParametersAdapter() {
        if( wiringParametersItemProvider == null ) {
            wiringParametersItemProvider = new WiringParametersItemProvider( this );
        }

        return wiringParametersItemProvider;
    }

    /**
     * This returns the root adapter factory that contains this factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public ComposeableAdapterFactory getRootAdapterFactory() {
        return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
    }

    /**
     * This sets the composed adapter factory that contains this factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public void setParentAdapterFactory( ComposedAdapterFactory parentAdapterFactory ) {
        this.parentAdapterFactory = parentAdapterFactory;
    }

    /**
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public boolean isFactoryForType( Object type ) {
        return supportedTypes.contains( type ) || super.isFactoryForType( type );
    }

    /**
     * This implementation substitutes the factory itself as the key for the adapter.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter adapt( Notifier notifier, Object type ) {
        return super.adapt( notifier, this );
    }

    /**
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Object adapt( Object object, Object type ) {
        if( isFactoryForType( type ) ) {
            Object adapter = super.adapt( object, type );
            if( !( type instanceof Class< ? > ) || ( ( ( Class< ? > ) type ).isInstance( adapter ) ) ) {
                return adapter;
            }
        }

        return null;
    }

    /**
     * This adds a listener.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public void addListener( INotifyChangedListener notifyChangedListener ) {
        changeNotifier.addListener( notifyChangedListener );
    }

    /**
     * This removes a listener.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public void removeListener( INotifyChangedListener notifyChangedListener ) {
        changeNotifier.removeListener( notifyChangedListener );
    }

    /**
     * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public void fireNotifyChanged( Notification notification ) {
        changeNotifier.fireNotifyChanged( notification );

        if( parentAdapterFactory != null ) {
            parentAdapterFactory.fireNotifyChanged( notification );
        }
    }

    /**
     * This disposes all of the item providers created by this factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public void dispose() {
        if( allocationRoleItemProvider != null ) {
            allocationRoleItemProvider.dispose();
        }
        if( allocationRoleRefItemProvider != null ) {
            allocationRoleRefItemProvider.dispose();
        }
        if( applicationItemProvider != null ) {
            applicationItemProvider.dispose();
        }
        if( analogueWiringParametersItemProvider != null ) {
            analogueWiringParametersItemProvider.dispose();
        }
        if( analogueWiringParametersRefItemProvider != null ) {
            analogueWiringParametersRefItemProvider.dispose();
        }
        if( applicationSclRefItemProvider != null ) {
            applicationSclRefItemProvider.dispose();
        }
        if( bayTypeItemProvider != null ) {
            bayTypeItemProvider.dispose();
        }
        if( behaviorDescriptionItemProvider != null ) {
            behaviorDescriptionItemProvider.dispose();
        }
        if( behaviorDescriptionRefItemProvider != null ) {
            behaviorDescriptionRefItemProvider.dispose();
        }
        if( behaviorReferenceItemProvider != null ) {
            behaviorReferenceItemProvider.dispose();
        }
        if( binaryWiringParametersItemProvider != null ) {
            binaryWiringParametersItemProvider.dispose();
        }
        if( binaryWiringParametersRefItemProvider != null ) {
            binaryWiringParametersRefItemProvider.dispose();
        }
        if( checkoutIDItemProvider != null ) {
            checkoutIDItemProvider.dispose();
        }
        if( controlRefItemProvider != null ) {
            controlRefItemProvider.dispose();
        }
        if( commServiceSpecificationsItemProvider != null ) {
            commServiceSpecificationsItemProvider.dispose();
        }
        if( controllingLNodeItemProvider != null ) {
            controllingLNodeItemProvider.dispose();
        }
        if( dasItemProvider != null ) {
            dasItemProvider.dispose();
        }
        if( dosItemProvider != null ) {
            dosItemProvider.dispose();
        }
        if( functionCategoryItemProvider != null ) {
            functionCategoryItemProvider.dispose();
        }
        if( functionCategoryRefItemProvider != null ) {
            functionCategoryRefItemProvider.dispose();
        }
        if( functionCatRefItemProvider != null ) {
            functionCatRefItemProvider.dispose();
        }
        if( functionRefItemProvider != null ) {
            functionRefItemProvider.dispose();
        }
        if( functionRoleItemProvider != null ) {
            functionRoleItemProvider.dispose();
        }
        if( functionRoleContentItemProvider != null ) {
            functionRoleContentItemProvider.dispose();
        }
        if( functionSclRefItemProvider != null ) {
            functionSclRefItemProvider.dispose();
        }
        if( functionTemplateItemProvider != null ) {
            functionTemplateItemProvider.dispose();
        }
        if( functionalSubVariantItemProvider != null ) {
            functionalSubVariantItemProvider.dispose();
        }
        if( functionalVariantItemProvider != null ) {
            functionalVariantItemProvider.dispose();
        }
        if( functionalVariantGroupItemProvider != null ) {
            functionalVariantGroupItemProvider.dispose();
        }
        if( functionalVariantRefItemProvider != null ) {
            functionalVariantRefItemProvider.dispose();
        }
        if( gooseParametersItemProvider != null ) {
            gooseParametersItemProvider.dispose();
        }
        if( gooseParametersRefItemProvider != null ) {
            gooseParametersRefItemProvider.dispose();
        }
        if( inputVarItemProvider != null ) {
            inputVarItemProvider.dispose();
        }
        if( inputVarRefItemProvider != null ) {
            inputVarRefItemProvider.dispose();
        }
        if( l2CommParametersItemProvider != null ) {
            l2CommParametersItemProvider.dispose();
        }
        if( l3IPv4CommParametersItemProvider != null ) {
            l3IPv4CommParametersItemProvider.dispose();
        }
        if( l3IPv6CommParametersItemProvider != null ) {
            l3IPv6CommParametersItemProvider.dispose();
        }
        if( lNodeDataRefItemProvider != null ) {
            lNodeDataRefItemProvider.dispose();
        }
        if( lNodeInputRefItemProvider != null ) {
            lNodeInputRefItemProvider.dispose();
        }
        if( lNodeInputsItemProvider != null ) {
            lNodeInputsItemProvider.dispose();
        }
        if( lNodeOutputRefItemProvider != null ) {
            lNodeOutputRefItemProvider.dispose();
        }
        if( lNodeOutputsItemProvider != null ) {
            lNodeOutputsItemProvider.dispose();
        }
        if( lNodeSpecNamingItemProvider != null ) {
            lNodeSpecNamingItemProvider.dispose();
        }
        if( logParametersItemProvider != null ) {
            logParametersItemProvider.dispose();
        }
        if( logParametersRefItemProvider != null ) {
            logParametersRefItemProvider.dispose();
        }
        if( logicVarRefItemProvider != null ) {
            logicVarRefItemProvider.dispose();
        }
        if( outputVarItemProvider != null ) {
            outputVarItemProvider.dispose();
        }
        if( outputVarRefItemProvider != null ) {
            outputVarRefItemProvider.dispose();
        }
        if( powerSystemRelationItemProvider != null ) {
            powerSystemRelationItemProvider.dispose();
        }
        if( powerSystemRelationRefItemProvider != null ) {
            powerSystemRelationRefItemProvider.dispose();
        }
        if( powerSystemRelationsItemProvider != null ) {
            powerSystemRelationsItemProvider.dispose();
        }
        if( processEchoItemProvider != null ) {
            processEchoItemProvider.dispose();
        }
        if( processResourceItemProvider != null ) {
            processResourceItemProvider.dispose();
        }
        if( processResourceRefItemProvider != null ) {
            processResourceRefItemProvider.dispose();
        }
        if( processResourcesItemProvider != null ) {
            processResourcesItemProvider.dispose();
        }
        if( projectItemProvider != null ) {
            projectItemProvider.dispose();
        }
        if( projectProcessReferenceItemProvider != null ) {
            projectProcessReferenceItemProvider.dispose();
        }
        if( reportParametersItemProvider != null ) {
            reportParametersItemProvider.dispose();
        }
        if( reportParametersRefItemProvider != null ) {
            reportParametersRefItemProvider.dispose();
        }
        if( resourceItemProvider != null ) {
            resourceItemProvider.dispose();
        }
        if( sdsItemProvider != null ) {
            sdsItemProvider.dispose();
        }
        if( serviceParametersRefItemProvider != null ) {
            serviceParametersRefItemProvider.dispose();
        }
        if( serviceSpecificationsItemProvider != null ) {
            serviceSpecificationsItemProvider.dispose();
        }
        if( signalRoleItemProvider != null ) {
            signalRoleItemProvider.dispose();
        }
        if( sourceRefItemProvider != null ) {
            sourceRefItemProvider.dispose();
        }
        if( subCategoryItemProvider != null ) {
            subCategoryItemProvider.dispose();
        }
        if( subCheckoutIDItemProvider != null ) {
            subCheckoutIDItemProvider.dispose();
        }
        if( subFunctionTemplateItemProvider != null ) {
            subFunctionTemplateItemProvider.dispose();
        }
        if( smvParametersItemProvider != null ) {
            smvParametersItemProvider.dispose();
        }
        if( smvParametersRefItemProvider != null ) {
            smvParametersRefItemProvider.dispose();
        }
        if( subscriberLNodeItemProvider != null ) {
            subscriberLNodeItemProvider.dispose();
        }
        if( variableItemProvider != null ) {
            variableItemProvider.dispose();
        }
        if( variableApplyToItemProvider != null ) {
            variableApplyToItemProvider.dispose();
        }
        if( variableRefItemProvider != null ) {
            variableRefItemProvider.dispose();
        }
        if( wiringParametersItemProvider != null ) {
            wiringParametersItemProvider.dispose();
        }
    }

}
