name: Build and test

# This CI workflow is triggered automatically for EVERY COMMIT or whenever a PULL REQUEST is OPENED/REOPENED
# It runs the building / testing workflow

on: 
  push: # Triggered every time on push
  pull_request: # Trigger on PR
    types: [opened, reopened]
  workflow_call: # Triggered manually for Release

jobs:
  call-build-test-workflow:
    name: Build & Test
    uses: riseclipse/riseclipse-workflows/.github/workflows/Build-Test.yml@master
    with:
      build-path: fr.centralesupelec.edf.riseclipse.iec61850.scl
    secrets:
      RISECLIPSE_PGP_KEY_PRIVATE:  ${{ secrets.RISECLIPSE_PGP_KEY_PRIVATE }}
      RISECLIPSE_PGP_KEY_PASSWORD: ${{ secrets.RISECLIPSE_PGP_KEY_PASSWORD }}
      RISECLIPSE_OSSRH_USERNAME:   ${{ secrets.RISECLIPSE_OSSRH_USERNAME }}
      RISECLIPSE_OSSRH_PASSWORD:   ${{ secrets.RISECLIPSE_OSSRH_PASSWORD }}