name: Release manual

on: workflow_dispatch  # Manual trigger only for master/main

jobs:
  call-build-test-workflow:
    name: Build & Test
    uses: riseclipse/riseclipse-workflows/.github/workflows/Build-Test.yml@master
    with:
      build-path: fr.centralesupelec.edf.riseclipse.iec61850.scl
  call-release-github-workflow:
    name: Release GH
    uses: riseclipse/riseclipse-workflows/.github/workflows/Release-GitHub.yml@master
  call-release-maven-workflow:
    name: Release MVN
    uses: riseclipse/riseclipse-workflows/.github/workflows/Release-Maven.yml@master
    with:
      build-path: fr.centralesupelec.edf.riseclipse.iec61850.scl