name: Rollback Failure

# If for some reason one of the release workflows failed, rollback and delete release branch

on:
  workflow_run:
    workflows: [Release Manual]
    types:
      - completed
    branches: [master, main]

jobs:
  call-failure-workflow:
    name: Rollback
    uses: riseclipse/riseclipse-workflows/.github/workflows/Release-Failure-Rollback.yml@master
    with:
      status: ${{ github.event.workflow_run.conclusion == 'failure' }}
      build-path: fr.centralesupelec.edf.riseclipse.iec61850.scl
